#!/bin/bash

# Assign stdin to keyboard
exec < /dev/tty

echo "Do you wish to update all submodules?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git submodule update --recursive --remote; break;;
        No ) exit;;
    esac
done
